### ISSUE TITLE
MPU error! -127

### ISSUE THREAD

**Issue by sssemil** [rpicopter/AvrMiniCopter-Arduino#1]
Hi, I've recompiled it with debugging enabled and it gives me this:

Free mem: 623
MPU error! -127
MPU init: 0
Free mem: 623
SPI packet corrupted!!0
MPU error! -127
MPU init: 0
Free mem: 623
MPU error! -127
MPU init: 0
...........

Any ideas on that?

I'm using RPi model B and Arduino Uno with bmp180 and mpu6050. As controller I`m using this - https://github.com/wilds/rpicopter-android-controller app on my phone and this - https://github.com/rpicopter/AvrMiniCopter-UDP on RPi.

Thanks.

**Comment by gregd72002** [comment]
Hi, MPU error -127 means that MPU is accumulating quicker data than it is being read by the program. This is usually caused by:
- too slow serial connection
- too much debug information being printed

You might also want to decrease the speed of MPU to 50 or lower:
https://github.com/rpicopter/AvrMiniCopter-Arduino/blob/master/AvrMiniCopter.ino#L793

What are you trying to debug?

**Comment by sssemil** [comment]
I was just checking if all connections are OK. Anyway it says "MPU init: 0" so I think it's connected correctly. I'll see if it works after buying motors and ESCs. Thanks again.

UPD: Changing mympu_open(mpu_addr,50,gyro_orientation); to mympu_open(mpu_addr,30,gyro_orientation); helped.
